version: '3'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-CU24-ubuntu-20.04
    ports:
      - "${MSSQL_PORT:-1433}:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD:?error}
    volumes:
      - mssql_data:/var/opt/mssql

volumes:
  mssql_data:
