name: .NET CI testing

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  DOTNET_VERSION: 8.0.x
  BUILD_CONFIG: Release

jobs:
  unit-tests:
    name: Unit testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - run: dotnet restore
      - run: dotnet build --no-restore --configuration ${{ env.BUILD_CONFIG }}
      - run: make test-unit

  integration-tests:
    name: Integration testing
    runs-on: ubuntu-latest
    env:
      DB_PROVIDER: sqlite
      CONN_STRING: Data Source=test.db
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - run: dotnet restore
      - run: dotnet build --no-restore --configuration ${{ env.BUILD_CONFIG }}
      - run: make test-integration